# Generated by Django 3.2 on 2021-07-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openinghours', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghour',
            name='restaurant',
        ),
    ]
